### ISSUE TITLE
PowerfulBackpacks for 1.21

### ISSUE THREAD

**Issue by puyafire** [FelipeRos19/PowerfulBackpacks#12]
Hi, I love this plugin so far but I have a minor issue. The backpacks can be placed inside other backpacks or inside the same backpack essentially dissappearing. I am not very good at this stuff so if I can be directed on how to fix this or if it is intended.

**Comment by FelipeRos19** [comment]
Hello! I'm glad to hear that you like the plugin! I'll update the plugin to fix these issues as soon as possible! ❤️

**Comment by puyafire** [comment]
Thx! I don't want to be pushy but is there an expected wait time?

**Comment by FelipeRos19** [comment]
No problem ^^, I'm in exam week at college so it's possible that I'll do all the updates on Wednesday next week.

**Comment by puyafire** [comment]
Sounds good I wish you the best of luck!!!!!

**Comment by FelipeRos19** [comment]
I came here to apologize, unfortunately I didn't have time to work on the project. I will try to work on the update during this week.

**Comment by David256** [comment]
To support multiple versions, do you create modules and each have a Spigot API version, or is there another infrastructure technique that is better for Spigot plugins? 🤔🤔🤔

**Comment by FelipeRos19** [comment]
Hello, first of all I would like to apologize infinitely for abandoning the project, many things ended up happening in the last few months and you probably won't use the plugin anymore but I released the version with support for 1.21

[New Release](https://github.com/FelipeRos19/PowerfulBackpacks/releases/tag/v1.2.1-1.21)
