### ISSUE TITLE
Can't seem to craft a backpack

### ISSUE THREAD

**Issue by ManicQuinn** [FelipeRos19/PowerfulBackpacks#3]
Paper 1.20.4
Added permission to LuckPerms, recipe doesn't seem to exist, tried to make a basic backpack itself and it still doesn't appear, not sure what to do.

**Comment by FelipeRos19** [comment]
Hello, could you send me your config.yml? so I can take a look

**Comment by FelipeRos19** [comment]
After some tests on Paper 1.20.4, it seems that all craftings work normally. But they are not in the recipe book, as they may have a customized item. This occours due to a limitation on Minecraft's recipe system (tho I am trying to find a workaround). If you're still having the same problem send the console information and your config.yml. Thanks for contacting!

**Comment by ManicQuinn** [comment]
> After some tests on Paper 1.20.4, it seems that all craftings work normally. But they are not in the recipe book, as they may have a customized item. This occours due to a limitation on Minecraft's recipe system (tho I am trying to find a workaround). If you're still having the same problem send the console information and your config.yml. Thanks for contacting!

My apologies, and yeah, still having the issues. It's probably a plugin incompatibility. I can send you my last log and config.
[aaaa.zip](https://github.com/FelipeRos19/PowerfulBackpacks/files/15220402/aaaa.zip)

**Comment by FelipeRos19** [comment]
Hello, checking the logs everything seems normal! Could you try to explain to me in more detail what happens when you try to craft a backpack, or record a video of the process. Checking the logs I didn't find any plugins that could cause a conflict.

**Comment by ManicQuinn** [comment]
> Hello, checking the logs everything seems normal! Could you try to explain to me in more detail what happens when you try to craft a backpack, or record a video of the process. Checking the logs I didn't find any plugins that could cause a conflict.

Well, I could record a video, but that would take a bit of worlk, so for now I'll just explain that when I craft it by putting leather in a table the same way you would craft a chest, it just doesn't show the backpack in the square where the completed craft would be.

**Comment by FelipeRos19** [comment]
Hello, first I would like to apologize for the delay in responding, I did several tests using the plugin with other inventory resources and crafting system, but I didn't have any problems with crafting the backpacks. The only change to the vanilla system is the reading of the "PrepareItemCraftEvent" event where I check if the items within the workbench are in the arrangement compatible with the recipes defined in Config.yml so the plugin does not change any of the game's default structures. At this point, I can only recommend that you analyze your list of plugins and look for one that changes this event that was mentioned previously.

**Comment by ManicQuinn** [comment]
> Hello, first I would like to apologize for the delay in responding, I did several tests using the plugin with other inventory resources and crafting system, but I didn't have any problems with crafting the backpacks. The only change to the vanilla system is the reading of the "PrepareItemCraftEvent" event where I check if the items within the workbench are in the arrangement compatible with the recipes defined in Config.yml so the plugin does not change any of the game's default structures. At this point, I can only recommend that you analyze your list of plugins and look for one that changes this event that was mentioned previously.

Yeah, fair, thank you
